/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package API.rest.assured.test;


import static io.restassured.RestAssured.basePath;
import static io.restassured.RestAssured.baseURI;
import static org.hamcrest.Matchers.*;

import API.rest.assured.dominio.Usuario;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;


import org.apache.http.util.Asserts;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

public class UsuarioTeste {

    @BeforeAll
        public static void setup(){
           RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
           baseURI = "https://reqres.in";
           basePath ="/api";
        }

    @Test
    public void testeListaMetadosUsuarios() {
        RestAssured.given().param("page","2").
        when()
                .get("/users").
                then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test
    public void criaUsuarioComSucesso() {
        Usuario usuario = new Usuario("Mateus","Analista de Sistema");

        RestAssured.given().
                contentType(ContentType.JSON).
                body(usuario).
                when().
                post("/users").
                then()
                .statusCode(201)
                .body("name", is("Mateus"));
    }

    @Test
    public void teste() {



    }



}
