/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package API.rest.assured.test;


import API.rest.assured.dominio.Usuario;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.Test;

import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;

public class UsuarioTeste extends BaseTeste{

    private static final String LISTA_USUARIOS_ENDPOINT ="/users";
    private static final String CRIAR_USUARIO_ENDDPOINT = "/user";


    @Test
    public void testeListaMetadosUsuarios() {
        RestAssured.given().param("page","2").
        when()
                .get(LISTA_USUARIOS_ENDPOINT).
                then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test
    public void criaUsuarioComSucesso() {
        Usuario usuario = new Usuario("Mateus","Analista de Sistema","mateusmorrais@gmail.com");

        RestAssured.given().
                body(usuario).
                when().
                post(CRIAR_USUARIO_ENDDPOINT).
                then()
                .statusCode(201)
                .body("name", is("Mateus"));
    }








}
